name: nbcourse
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install pandoc
      run: |
        sudo apt-get -yq update
        sudo apt-get install -yq pandoc texlive-xetex texlive-fonts-extra
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Install Julia
      run: julia -e 'using Pkg; Pkg.add(["IJulia","Plots","StatsPlots","DataFrames"]); Pkg.build("IJulia")'
    - name: Install Miniconda
      uses: goanpeca/setup-miniconda@v1
      with:
        miniconda-version: "latest"
    - name: Install dependencies and run nbcourse
      shell: bash -l {0}
      run: |
        conda env update -f environment.yml -n runenv
        conda run -n runenv python -m ipykernel install --user --name python3
        conda run -n base python -m pip install --ignore-installed nbcourse
        conda run -n base nbcourse -n 1
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build
